# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e14b20cebf2e6de896121b546a690d4d31f0fdafb40e50a00aae6a7733a0ca44e28c87b0e1d7436f65b38d781e40c922dc495fb7be1f958163349d7de47186

test:
  secret_key_base: b3f3e9ae336d9387037ddd447be6cce3b99b29b968f5b2072c3736dbfdced86d513c98ad72fd85121d8906511171b4eab35172bcc016818f5f179b05ceb7769a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
